#!/bin/csh

echo "<UNIX-PROMPT> pwd"
pwd
echo "<UNIX-PROMPT> ls -tl *java"
ls -tl *java
echo "<UNIX-PROMPT> cat Test_TrafficModel.java"
cat Test_TrafficModel.java
echo "<UNIX-PROMPT> cat TrafficModel.java"
cat TrafficModel.java
echo "<UNIX-PROMPT> cat Intersection.java"
cat Intersection.java
echo "<UNIX-PROMPT> cat Segment.java"
cat Segment.java
echo "<UNIX-PROMPT> cat Car.java"
cat Car.java
echo "<UNIX-PROMPT> cat Direction.java"
cat Direction.java
echo "<UNIX-PROMPT> cat Turn.java"
cat Turn.java
echo "<UNIX-PROMPT> cat data1_for_checking_top_level_logic"
cat data1_for_checking_top_level_logic
echo "<UNIX-PROMPT> rm *class"
rm *class
echo "<UNIX-PROMPT> javac Test_TrafficModel.java"
javac Test_TrafficModel.java
echo "<UNIX-PROMPT> javac TrafficModel.java"
javac TrafficModel.java
echo "<UNIX-PROMPT> javac Intersection.java"
javac Intersection.java
echo "<UNIX-PROMPT> javac Segment.java"
javac Segment.java
echo "<UNIX-PROMPT> javac Car.java"
javac Car.java
echo "<UNIX-PROMPT> javac Direction.java"
javac Direction.java
echo "<UNIX-PROMPT> javac Turn.java"
javac Turn.java
echo "<UNIX-PROMPT> java Test_TrafficModel < data1_for_checking_top_level_logic"
java Test_TrafficModel < data1_for_checking_top_level_logic

